### PR TITLE
fix getLogs

### LINKED ISSUE #158: `eth_getLogs` not working as expected
ganache response to `eth_getLogs`:
```
curl http://localhost:8545 \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","method":"eth_getLogs","params": [{ "fromBlock": "0x4", "toBlock": "0x5", "topics": []}],"id":1}' 
{"id":1,"jsonrpc":"2.0","result":[{"logIndex":"0x0","transactionIndex":"0x0","transactionHash":"0xa3efd4fc42f9c7184f23ec4d7b62b626521e3dda3768a8e61bc87e0ec953b097","blockHash":"0x62850366828e24eeb0c0df6b7a010a24b926278951d9195f386dbff2a9c92c7b","blockNumber":"0x4","address":"0x217b896620aff6518b9862160606695607a63442","data":"0x","topics":["0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0","0x0000000000000000000000000000000000000000000000000000000000000000","0x00000000000000000000000075e480db528101a381ce68544611c169ad7eb342"],"type":"mined","removed":false}]}%  
```

bodhi.js response
```
curl http://localhost:8545 \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","method":"eth_getLogs","params": [{ "fromBlock": "0x4", "toBlock": "0x5", "topics": []}],"id":1}'
{"id":1,"jsonrpc":"2.0","error":{"code":-32602,"message":"blocktag should be number | 'latest' | 'earliest' (argument=\"blockTag\", value=\"0x4\", code=INVALID_ARGUMENT, version=bodhi.js/providers/2.1.4)"}}% 
```

https://github.com/AcalaNetwork/bodhi.js/issues/95
https://github.com/AcalaNetwork/bodhi.js/pull/104

### PR DESCRIPTION
**Pull request by ntduan**
fix #158

### CODE REVIEW

**Comment by gluneau** [comment]
@shunjizhan Can you make a release and publish on Mandala when merged?

**Comment by shunjizhan** [comment]
sure, I will do a manual release when merged. 
Do we now need a new release for every merge, since ppl are using public build instead of pulling bodhi locally? If so I think we should better figure out a way to auto publish for every commit

**Comment by shunjizhan** [comment]
just published a new release https://github.com/AcalaNetwork/bodhi-deplopyment/commits/master

**Comment by gluneau** [comment]
It's more nuanced that every commit.  It it is a protocol correction or an important fix that is going into production, then we make a release.  In fact releases should probably mirror what goes into production, every time bodhi is push into prod, a release should be made!  That way, a dev wanting to replicate what is in prod can easily do so, therefore can plan and prepare and test their deployments against it.

**Pull request merged**
