### PR TITLE
fix author address

### PR DESCRIPTION
**Pull request by ntduan**

### CODE REVIEW

**Review by gluneau — COMMENTED** [review]
Looks good to me.

As long as we start with this:
Mnemonic:      fox sight canyon orphan hotel grow hedgehog build bless august weather swarm
Private Key: 0xa872f6cbd25a0e04a08b1e21098017a9e6194d101d75e13111f71410c59cd57f

we get this Public Key: 0x75E480dB528101a381Ce68544611C169Ad7EB342

**Review by xlc — APPROVED** [review]

**Comment by xlc** [comment]
This is for block author, have nothing to do with private key derivation

**Comment by gluneau** [comment]
> This is for block author, have nothing to do with private key derivation @gluneau

ok, so this is the block "miner" address then?

**Comment by xlc** [comment]
yes. just expose the block author address with eth format

**Review by gluneau — APPROVED** [review]

**Pull request merged**
