### PR TITLE
pack eth-rpc-adapter to reduce docker image

### PR DESCRIPTION
**Pull request by ermalkaleci**
uncompressed image from 3GB to 130Mb

### CODE REVIEW

**Comment by ermalkaleci** [comment]
uncompressed image from 3GB to 100Mb

**Comment by ermalkaleci** [comment]
@shunjizhan can you give this a try?

**Review by shunjizhan — APPROVED** [review]
tried it out, looks good to me

**Comment by shunjizhan** [comment]
by the way if we are going to use this image in prod, it might be worth to update CI build to use ncc too, which makes prod and test more consistent

**Pull request merged**
