### PR TITLE
added eth_gasPrice to eip adaptor

### PR DESCRIPTION
**Pull request by shunjizhan**
## Change
added eth_gasPrice to eip adaptor

## Test
```
GET
{
	"jsonrpc":"2.0",
	"method":"eth_gasPrice",
	"params":[],
	"id":1
}
```
```
{
    "id": 1,
    "jsonrpc": "2.0",
    "result": "0x01"
}
```

### CODE REVIEW

**Review by ntduan — APPROVED** [review]

**Comment by gluneau** [comment]
Great, this was required by the Kreatr smart contract test

**Comment by gluneau** [comment]
Hello @shunjizhan are we hardcoding `0x01` and expect it to work?  What am I missing?

`npx hardhat run scripts/sample-script.js --network development`

``` 
HardhatError: HH107: Received invalid value `0x01` from/to the node's JSON-RPC, but a Quantity was expected.
    at Object.rpcQuantityToBN (/home/hardhat/node_modules/hardhat/src/internal/core/jsonrpc/types/base-types.ts:73:11)
    at AutomaticGasPriceProvider._getGasPrice (/home/hardhat/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:220:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at AutomaticGasPriceProvider.request (/home//hardhat/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:180:41)
    at EthersProviderWrapper.send (/home/hardhat/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20
```

Test with infura and then local:
```
curl https://mainnet.infura.io/v3/54b...9da \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","method":"eth_gasPrice","params": [],"id":1}'
{"jsonrpc":"2.0","id":1,"result":"0x18c386501a"}

curl http://localhost:8545 \                                        
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","method":"eth_gasPrice","params": [],"id":1}'
{"id":1,"jsonrpc":"2.0","result":"0x01"}
```

**Comment by ntduan** [comment]
> 你好@shunjizhan我们是硬编码`0x01`并期望它起作用吗？我错过了什么？
> 
> `npx hardhat run scripts/sample-script.js --network development`
> 
> ```
> HardhatError: HH107: Received invalid value `0x01` from/to the node's JSON-RPC, but a Quantity was expected.
>     at Object.rpcQuantityToBN (/home/hardhat/node_modules/hardhat/src/internal/core/jsonrpc/types/base-types.ts:73:11)
>     at AutomaticGasPriceProvider._getGasPrice (/home/hardhat/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:220:12)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
>     at AutomaticGasPriceProvider.request (/home//hardhat/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:180:41)
>     at EthersProviderWrapper.send (/home/hardhat/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20
> ```
> 
> 使用 infura 进行测试，然后在本地进行测试：
> 
> ```
> curl https://mainnet.infura.io/v3/54b...9da \
>     -X POST \
>     -H "Content-Type: application/json" \
>     -d '{"jsonrpc":"2.0","method":"eth_gasPrice","params": [],"id":1}'
> {"jsonrpc":"2.0","id":1,"result":"0x18c386501a"}
> 
> curl http://localhost:8545 \                                        
>     -X POST \
>     -H "Content-Type: application/json" \
>     -d '{"jsonrpc":"2.0","method":"eth_gasPrice","params": [],"id":1}'
> {"id":1,"jsonrpc":"2.0","result":"0x01"}
> ```

Yes, it's hardcoded, the gas_price stuff doesn't exist in our chain.

**Comment by ntduan** [comment]
> Hello @shunjizhan are we hardcoding `0x01` and expect it to work? What am I missing?
> 
> `npx hardhat run scripts/sample-script.js --network development`
> 
> ```
> HardhatError: HH107: Received invalid value `0x01` from/to the node's JSON-RPC, but a Quantity was expected.
>     at Object.rpcQuantityToBN (/home/hardhat/node_modules/hardhat/src/internal/core/jsonrpc/types/base-types.ts:73:11)
>     at AutomaticGasPriceProvider._getGasPrice (/home/hardhat/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:220:12)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
>     at AutomaticGasPriceProvider.request (/home//hardhat/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:180:41)
>     at EthersProviderWrapper.send (/home/hardhat/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20
> ```
> 
> Test with infura and then local:
> 
> ```
> curl https://mainnet.infura.io/v3/54b...9da \
>     -X POST \
>     -H "Content-Type: application/json" \
>     -d '{"jsonrpc":"2.0","method":"eth_gasPrice","params": [],"id":1}'
> {"jsonrpc":"2.0","id":1,"result":"0x18c386501a"}
> 
> curl http://localhost:8545 \                                        
>     -X POST \
>     -H "Content-Type: application/json" \
>     -d '{"jsonrpc":"2.0","method":"eth_gasPrice","params": [],"id":1}'
> {"id":1,"jsonrpc":"2.0","result":"0x01"}
> ```

Yes, it's hardcoded, the gas_price stuff doesn't exist in our chain.

**Comment by ntduan** [comment]
> Hello @shunjizhan are we hardcoding `0x01` and expect it to work? What am I missing?
> 
> `npx hardhat run scripts/sample-script.js --network development`
> 
> ```
> HardhatError: HH107: Received invalid value `0x01` from/to the node's JSON-RPC, but a Quantity was expected.
>     at Object.rpcQuantityToBN (/home/hardhat/node_modules/hardhat/src/internal/core/jsonrpc/types/base-types.ts:73:11)
>     at AutomaticGasPriceProvider._getGasPrice (/home/hardhat/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:220:12)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
>     at AutomaticGasPriceProvider.request (/home//hardhat/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:180:41)
>     at EthersProviderWrapper.send (/home/hardhat/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20
> ```
> 
> Test with infura and then local:
> 
> ```
> curl https://mainnet.infura.io/v3/54b...9da \
>     -X POST \
>     -H "Content-Type: application/json" \
>     -d '{"jsonrpc":"2.0","method":"eth_gasPrice","params": [],"id":1}'
> {"jsonrpc":"2.0","id":1,"result":"0x18c386501a"}
> 
> curl http://localhost:8545 \                                        
>     -X POST \
>     -H "Content-Type: application/json" \
>     -d '{"jsonrpc":"2.0","method":"eth_gasPrice","params": [],"id":1}'
> {"id":1,"jsonrpc":"2.0","result":"0x01"}
> ```

Changing 0x01 to 0x1 will fix this issue

**Pull request merged**
