### PR TITLE
Add pre commit

### PR DESCRIPTION
**Pull request by ntduan**
add git pre commit hook. Using prettier for automatic formatting

### CODE REVIEW

**Review by zjb0807 — APPROVED** [review]

**Comment by shunjizhan** [comment]
@ntduan can you also create PRs for the tutorials? so when @ThunderDeliverer updates the tutorials, it will be based on this, otherwise branches will diverge, thanks

**Comment by shunjizhan** [comment]
we should better keep tutorials master branch same as bodhi's submodules

**Comment by ntduan** [comment]
> we should better keep tutorials master branch same as bodhi's submodules

the prs has been created

**Comment by shunjizhan** [comment]
thanks!

**Pull request merged**
