### PR TITLE
Update examples

### PR DESCRIPTION
**Pull request by zjb0807**
https://github.com/AcalaNetwork/truffle-tutorials/pull/28
https://github.com/AcalaNetwork/hardhat-tutorials/pull/54
https://github.com/AcalaNetwork/waffle-tutorials/pull/13

https://github.com/AcalaNetwork/hardhat-tutorials/pull/58
https://github.com/AcalaNetwork/truffle-tutorials/pull/33

TODO:
- [x] evm-accounts
- [x] homa
- [x] honzon
- [x] incentives

### CODE REVIEW

**Comment by shunjizhan** [comment]
@ThunderDeliverer I noticed advanced escrow had some weird failure in CI, despite the fact that running it alone locally can pass. Could it be some flaky expectation that only works in some certain circumstances?

For example the latest CI run in this branch https://github.com/AcalaNetwork/bodhi.js/runs/7262955497?check_suite_focus=true
```hardhat-tutorials-test_1                 |   14 passing (2m)
hardhat-tutorials-test_1                 |   4 failing
hardhat-tutorials-test_1                 |
hardhat-tutorials-test_1                 |   1) AdvancedEscrow contract
hardhat-tutorials-test_1                 |        Operation
hardhat-tutorials-test_1                 |          should set the values of current escrow when initiating the escrow:
hardhat-tutorials-test_1                 |      AssertionError: Expected "214" to be equal 215
hardhat-tutorials-test_1                 |       at Context.<anonymous> (test/AdvancedEscrow.js:112:34)
hardhat-tutorials-test_1                 |       at runMicrotasks (<anonymous>)
hardhat-tutorials-test_1                 |       at processTicksAndRejections (node:internal/process/task_queues:96:5)
hardhat-tutorials-test_1                 |
hardhat-tutorials-test_1                 |   2) AdvancedEscrow contract
hardhat-tutorials-test_1                 |        Operation
hardhat-tutorials-test_1                 |          should revert when initiating a new escrow when there is a preexiting active escrow:
hardhat-tutorials-test_1                 |
hardhat-tutorials-test_1                 |       AssertionError: Expected transaction to be reverted
hardhat-tutorials-test_1                 |       + expected - actual
hardhat-tutorials-test_1                 |
hardhat-tutorials-test_1                 |       -Transaction NOT reverted.
hardhat-tutorials-test_1                 |       +Transaction reverted.
hardhat-tutorials-test_1                 |
hardhat-tutorials-test_1                 |
hardhat-tutorials-test_1                 |
hardhat-tutorials-test_1                 |   3) AdvancedEscrow contract
hardhat-tutorials-test_1                 |        Operation
hardhat-tutorials-test_1                 |          should update the egress token:
hardhat-tutorials-test_1                 |      AssertionError: Expected "255" to be equal 256
hardhat-tutorials-test_1                 |       at Context.<anonymous> (test/AdvancedEscrow.js:171:34)
hardhat-tutorials-test_1                 |       at runMicrotasks (<anonymous>)
hardhat-tutorials-test_1                 |       at processTicksAndRejections (node:internal/process/task_queues:96:5)
hardhat-tutorials-test_1                 |
hardhat-tutorials-test_1                 |   4) AdvancedEscrow contract
hardhat-tutorials-test_1                 |        Operation
hardhat-tutorials-test_1                 |          should revert when trying to complete an escrow when not being the initiator:
hardhat-tutorials-test_1                 |      AssertionError: Expected transaction to be reverted with Escrow: caller is not initiator or this contract, but other exception was thrown: ProviderError: Error: -32603: VM Exception while processing transaction: execution revert Escrow: escrow already completed: 0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000020457363726f773a20657363726f7720616c726561647920636f6d706c65746564
```

**Comment by ThunderDeliverer** [comment]
@shunjizhan [https://github.com/AcalaNetwork/hardhat-tutorials/pull/58/commits/e2477c6143cc8fbc3ee5f9159874bf0438443c1c](https://github.com/AcalaNetwork/hardhat-tutorials/pull/58/commits/e2477c6143cc8fbc3ee5f9159874bf0438443c1c) fixes the issue by moving the `loop` util from `test` to `utils` directory

**Review by shunjizhan — APPROVED** [review]
finally it passed :tada:

**Comment by shunjizhan** [comment]
let's merge hardhat/truffle tutorials first, and update reference to their master before merging

**Pull request merged**
