### PR TITLE
fix hex blocknumber

### LINKED ISSUE #158: `eth_getLogs` not working as expected
ganache response to `eth_getLogs`:
```
curl http://localhost:8545 \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","method":"eth_getLogs","params": [{ "fromBlock": "0x4", "toBlock": "0x5", "topics": []}],"id":1}' 
{"id":1,"jsonrpc":"2.0","result":[{"logIndex":"0x0","transactionIndex":"0x0","transactionHash":"0xa3efd4fc42f9c7184f23ec4d7b62b626521e3dda3768a8e61bc87e0ec953b097","blockHash":"0x62850366828e24eeb0c0df6b7a010a24b926278951d9195f386dbff2a9c92c7b","blockNumber":"0x4","address":"0x217b896620aff6518b9862160606695607a63442","data":"0x","topics":["0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0","0x0000000000000000000000000000000000000000000000000000000000000000","0x00000000000000000000000075e480db528101a381ce68544611c169ad7eb342"],"type":"mined","removed":false}]}%  
```

bodhi.js response
```
curl http://localhost:8545 \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","method":"eth_getLogs","params": [{ "fromBlock": "0x4", "toBlock": "0x5", "topics": []}],"id":1}'
{"id":1,"jsonrpc":"2.0","error":{"code":-32602,"message":"blocktag should be number | 'latest' | 'earliest' (argument=\"blockTag\", value=\"0x4\", code=INVALID_ARGUMENT, version=bodhi.js/providers/2.1.4)"}}% 
```

https://github.com/AcalaNetwork/bodhi.js/issues/95
https://github.com/AcalaNetwork/bodhi.js/pull/104

### PR DESCRIPTION
**Pull request by ntduan**
fix #158 #157

### CODE REVIEW

**Comment by ntduan** [comment]
@gluneau  Can you test if this pr can fix those two issues?

**Comment by gluneau** [comment]
I don't think it worked.  it returns nothing when blocks are found.  
```
[1638312360766] DEBUG (1780071 on XPS-15-7590): incoming request
    jsonrpc: "2.0"
    method: "eth_getLogs"
    params: [
      {
        "fromBlock": "0x4",
        "toBlock": "0x5",
        "topics": []
      }
    ]
    id: 1
[1638312360809] DEBUG (1780071 on XPS-15-7590): request completed
    id: 1
    jsonrpc: "2.0"
    result: []
```

also I think it was not able to deploy the contract, hence it waited for 20 tries and failled.

```
failed attemp # 20/20
[1638312331120] ERROR (1780071 on XPS-15-7590): request error
    methodName: "eth_getTransactionByHash"
    params: [
      "0xea942b45fcfe283a696d0e42d9f9fae01c1882b9d94f736c08958ddef918dc80"
    ]
    err: {
      "type": "Error",
      "message": "transaction hash not found (txHash=\"0xea942b45fcfe283a696d0e42d9f9fae01c1882b9d94f736c08958ddef918dc80\", code=UNKNOWN_ERROR, version=bodhi.js/providers/2.1.4)",
      "stack":
          Error: transaction hash not found (txHash="0xea942b45fcfe283a696d0e42d9f9fae01c1882b9d94f736c08958ddef918dc80", code=UNKNOWN_ERROR, version=bodhi.js/providers/2.1.4)
              at Logger.makeError (/home/bodhi.js/common/temp/node_modules/.pnpm/@ethersproject+logger@5.4.1/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
              at Logger.throwError (/home/bodhi.js/common/temp/node_modules/.pnpm/@ethersproject+logger@5.4.1/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)
              at EvmRpcProvider.BaseProvider._getTXReceipt (/home/bodhi.js/eth-providers/lib/base-provider.js:593:32)
              at processTicksAndRejections (internal/process/task_queues.js:95:5)
              at async BaseProvider.getTransactionByHash (/home/bodhi.js/eth-providers/lib/base-provider.js:598:24)
              at async Eip1193BridgeImpl._runWithRetries (/home/bodhi.js/eth-rpc-adapter/src/eip1193-bridge.ts:238:15)
              at async Eip1193BridgeImpl.eth_getTransactionByHash (/home/bodhi.js/eth-rpc-adapter/src/eip1193-bridge.ts:259:17)
              at async Router.call (/home/bodhi.js/eth-rpc-adapter/src/router.ts:16:24)
              at async HTTPServerTransport.routerHandler (/home/bodhi.js/eth-rpc-adapter/src/transports/server-transport.ts:60:13)
              at async HTTPServerTransport.httpRouterHandler (/home/bodhi.js/eth-rpc-adapter/src/transports/http.ts:58:16)
      "reason": "transaction hash not found",
      "code": "UNKNOWN_ERROR",
      "txHash": "0xea942b45fcfe283a696d0e42d9f9fae01c1882b9d94f736c08958ddef918dc80"
    }
[1638312331168] DEBUG (1780071 on XPS-15-7590): request completed
    id: "9707e3b0"
    jsonrpc: "2.0"
    error: {
      "code": 6969,
      "message": "Error: transaction hash not found (txHash=\"0xea942b45fcfe283a696d0e42d9f9fae01c1882b9d94f736c08958ddef918dc80\", code=UNKNOWN_ERROR, version=bodhi.js/providers/2.1.4)"
    }
```

**Comment by ntduan** [comment]
> I don't think it worked. it returns nothing when blocks are found.
> 
> ```
> [1638312360766] DEBUG (1780071 on XPS-15-7590): incoming request
>     jsonrpc: "2.0"
>     method: "eth_getLogs"
>     params: [
>       {
>         "fromBlock": "0x4",
>         "toBlock": "0x5",
>         "topics": []
>       }
>     ]
>     id: 1
> [1638312360809] DEBUG (1780071 on XPS-15-7590): request completed
>     id: 1
>     jsonrpc: "2.0"
>     result: []
> ```
> 
> also I think it was not able to deploy the contract, hence it waited for 20 tries and failled.
> 
> ```
> failed attemp # 20/20
> [1638312331120] ERROR (1780071 on XPS-15-7590): request error
>     methodName: "eth_getTransactionByHash"
>     params: [
>       "0xea942b45fcfe283a696d0e42d9f9fae01c1882b9d94f736c08958ddef918dc80"
>     ]
>     err: {
>       "type": "Error",
>       "message": "transaction hash not found (txHash=\"0xea942b45fcfe283a696d0e42d9f9fae01c1882b9d94f736c08958ddef918dc80\", code=UNKNOWN_ERROR, version=bodhi.js/providers/2.1.4)",
>       "stack":
>           Error: transaction hash not found (txHash="0xea942b45fcfe283a696d0e42d9f9fae01c1882b9d94f736c08958ddef918dc80", code=UNKNOWN_ERROR, version=bodhi.js/providers/2.1.4)
>               at Logger.makeError (/home/bodhi.js/common/temp/node_modules/.pnpm/@ethersproject+logger@5.4.1/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
>               at Logger.throwError (/home/bodhi.js/common/temp/node_modules/.pnpm/@ethersproject+logger@5.4.1/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)
>               at EvmRpcProvider.BaseProvider._getTXReceipt (/home/bodhi.js/eth-providers/lib/base-provider.js:593:32)
>               at processTicksAndRejections (internal/process/task_queues.js:95:5)
>               at async BaseProvider.getTransactionByHash (/home/bodhi.js/eth-providers/lib/base-provider.js:598:24)
>               at async Eip1193BridgeImpl._runWithRetries (/home/bodhi.js/eth-rpc-adapter/src/eip1193-bridge.ts:238:15)
>               at async Eip1193BridgeImpl.eth_getTransactionByHash (/home/bodhi.js/eth-rpc-adapter/src/eip1193-bridge.ts:259:17)
>               at async Router.call (/home/bodhi.js/eth-rpc-adapter/src/router.ts:16:24)
>               at async HTTPServerTransport.routerHandler (/home/bodhi.js/eth-rpc-adapter/src/transports/server-transport.ts:60:13)
>               at async HTTPServerTransport.httpRouterHandler (/home/bodhi.js/eth-rpc-adapter/src/transports/http.ts:58:16)
>       "reason": "transaction hash not found",
>       "code": "UNKNOWN_ERROR",
>       "txHash": "0xea942b45fcfe283a696d0e42d9f9fae01c1882b9d94f736c08958ddef918dc80"
>     }
> [1638312331168] DEBUG (1780071 on XPS-15-7590): request completed
>     id: "9707e3b0"
>     jsonrpc: "2.0"
>     error: {
>       "code": 6969,
>       "message": "Error: transaction hash not found (txHash=\"0xea942b45fcfe283a696d0e42d9f9fae01c1882b9d94f736c08958ddef918dc80\", code=UNKNOWN_ERROR, version=bodhi.js/providers/2.1.4)"
>     }
> ```

Well, at least the errors are different.  I'll merge this pr. @shunjizhan Can you look at why the data query is empty.

**Comment by shunjizhan** [comment]
I just made a fresh clone of bodhi and tested with warmwhole, it is able to deploy. Also, I think it is normal that logs are empty, since there is no transactions yet. If we feed some tx data, such as using `examples/waffle/dex`, we will be able to see logs

**Comment by shunjizhan** [comment]
but I do get some other test failures (that previously passed)... will look at them later

**Pull request merged**
