### PR TITLE
Add tutorials

### PR DESCRIPTION
**Pull request by ThunderDeliverer**
Hardhat, Truffle and Waffle tutorials were added as submodules.
Additionally they were added to rush as projects so that they can be run in the CI and added to the CI pipeline.

### CODE REVIEW

**Comment by shunjizhan** [comment]
thanks Jan, there are some merge conflicts we need to solve, in particular:
- master branch renamed `build-on-push.yml` to `unit-test.yml`
- need to change `e2e-test.yml config to deal with the new truffle/hardhat structure (I can do this on my end)

**Comment by shunjizhan** [comment]
when I ran the hardhat examples with mandala 2.1.0, tests were failing and I think we need to specify gasPrice and gasLimit like this for every call
https://github.com/AcalaNetwork/bodhi.js/blob/master/examples/hardhat/test/HelloWorld.test.ts#L20-L21

**Comment by shunjizhan** [comment]
follow up for the failing examples: I think these runs reflect the latest failing info for your reference, please let me know if any of these failures doesn't make sense or couldn't reproduce locally
- https://github.com/AcalaNetwork/bodhi.js/runs/4593421014?check_suite_focus=true
- https://github.com/AcalaNetwork/bodhi.js/runs/4593420802?check_suite_focus=true
- https://github.com/AcalaNetwork/bodhi.js/runs/4593420686?check_suite_focus=true

**Comment by shunjizhan** [comment]
@ThunderDeliverer Hey Jan, in order to rebase this branch on top of master, do you prefer me to rebase + force push, or rebase + new PR?

**Comment by ThunderDeliverer** [comment]
Rebase and force push with `--force-with-lease` flag would have been ok in this case. Let's close this one as we have a new pull request opened. 👌

**Comment by shunjizhan** [comment]
great to know that flag, will try it next time lol

**Pull request closed without merging**
