### PR TITLE
Add linkdrop contract

### PR DESCRIPTION
**Pull request by ntduan**

### CODE REVIEW

**Comment by shunjizhan** [comment]
Hey Nantian, @ThunderDeliverer have already restruct the tutorials and examples as submodules https://github.com/AcalaNetwork/bodhi.js/pull/199

I wonder how should we proceed with linkdrop contracts? I am fine with either copy them directly in here, or also make it submodules. Maybe we can have a discussion with @ThunderDeliverer just to sync our decisions.

**Comment by shunjizhan** [comment]
The reason we haven't merge that branch is we are waiting for #220 to be merged, and update all the tutorials accordingly

**Comment by ntduan** [comment]
This pr is not urgent and not necessary. I have already committed the updated code to the master branch. This pr can wait until later to decide if a merge is necessary.

**Comment by shunjizhan** [comment]
@ntduan do we still need this? If not I will close it

**Comment by ntduan** [comment]
> @ntduan do we still need this? If not I will close it

I don't think it's necessary anymore

**Pull request closed without merging**
